### ISSUE TITLE
Missing Printer Driver Brother MFC-7460DN

### ISSUE THREAD

**Issue by AlexanderSch90** [RagingTiger/docker-cups-airprint#14]
hey, I read in the last issue that the repo [Brlaser](https://github.com/pdewacht/brlaser) is added. The Brother MFC-7460DN printer is also part of the repo. Unfortunately I cannot find or add the printer in the drop-down menu. What am I doing wrong? Thanks

**Comment by RagingTiger** [comment]
Assuming everything else is working, it could be that the `printer driver` installed on the `tigerj/cups-airprint` *Docker image* is old. This is the problem we ran into on #9.

The fix there was to work with the `dev` branch which can be pulled using `tigerj/cups-airprint:dev` or building from source by pulling down the `git repo` and *checking out* the `dev` branch.

Granted, this all assumes everything else you've done to configure/setup your *Docker container* is correct. You could try using the `dev` branch and see if that helps.

Or if it doesn't then you'll need to paste all the *Docker* commands you used to run your container, and any other relevant info (i.e. printer brand/model, Docker host architecture, etc ...).

Let us know 😄
