### ISSUE TITLE
Lexmark X9575

### ISSUE THREAD

**Issue by Rakth** [RagingTiger/docker-cups-airprint#15]
Hi

Can you install the Lexmark X9575 drivers into the package?

**Comment by RagingTiger** [comment]
This is most likely a bit _beyond_ my expertise. After a quick search, this is what I could find that made some sense: https://lists.cups.org/pipermail/cups/2017-April/073601.html.

What exactly have you tried already? Have you tried using the **Docker image** and did it not work?

**Comment by RagingTiger** [comment]
Closing ahead of _repository archiving_. Please see _forks_ for possible solutions to your **use case** or consider forking and implementing your own solution :)
