### ISSUE TITLE
Print jobs stuck - Failed to open PPD: /etc/cups/ppd/OfficePrinter.ppdk

### ISSUE THREAD

**Issue by fabriziorizzo** [RagingTiger/docker-cups-airprint#4]
Is there something additional that needs to be done?
Every job gets stuck in the queue with the error:  Failed to open PPD: /etc/cups/ppd/OfficePrinter.ppd

Printer details:

```
Queue Name | Description | Location | Make and Model | Status
-- | -- | -- | -- | --
OfficePrinter | EPSON Artisan 830 | 8455 Office | Epson Artisan 835 - CUPS+Gutenprint v5.2.11 | Processing - "Unable to locate printer "FRPEPSON835.local"."
```

I configured my printer just fine (Epson Artisan 835) from the web interface and I see the printer in .../config/printers.conf along with the .../config/ppd/OfficePrinter.ppd and OfficePrinter.ppd.0 files

```
[/share/docker/cups-data/config] # docker exec -i -t cups ls -al /etc/cups/ppd  
lrwxrwxrwx 1 root root 11 Jan 23 17:55 /etc/cups/ppd -> /config/ppd

[/share/docker/cups-data/config] # docker exec -i -t cups ls -al /config/ppd  
total 400
drwxrwx---+ 2 root root   4096 Jan 23 17:59 .
drwxrwx---+ 3 root root   4096 Jan 23 17:55 ..
-rw-r-----+ 1 root lp   193984 Jan 23 17:59 OfficePrinter.ppd
-rw-r-----+ 1 root lp   193957 Jan 23 17:58 OfficePrinter.ppd.O
```

The printer shows up in AirPrint and queues jobs just fine.

How do I fix this please?

**Comment by RagingTiger** [comment]
My instinct is to say this sound like a `permissions` issue.

How are you building the `cups` container shown in your examples above?

Also, you might find the following reference of interest: https://askubuntu.com/questions/778970/printer-stack-on-processing-failed-to-read-ppd-file

**Comment by fabriziorizzo** [comment]
Building simply with docker create, start...  Running in QNAP Container Station.

```
[admin] # mkdir -p /share/docker/cups-data/config
[admin] #  mkdir -p /share/docker/cups-data/settings

[admin] #  docker create \
       --name=cups \
       --restart=always \
       --net=host \
       -v /var/run/dbus:/var/run/dbus \
       -v /share/docker/cups-data/config:/config \
       -v /share/docker/cups-data/settings:/services \
       --device /dev/bus \
       -e CUPSADMIN="admin" \
       -e CUPSPASSWORD="password" \
       tigerj/cups-airprint

[admin] #  docker start cups
```

browser:  http://nas.mydomain:631/admin
added network printer...

iphone:  browse to a webpage > share > print:  airprint device appears, selected, sent to printer

browser: http://nas.mydomain:631/jobs
job appears in "processing" state, with ""Failed to open PPD: /etc/cups/ppd/OfficePrinter.ppd" error message.

```
[admin] #  docker stop cups

[admin] #  chmod o+rx /share/docker/cups-data/config/ppd
[admin] #  chmod o+r /share/docker/cups-data/config/ppd/*
[admin] #  ls -al /share/docker/cups-data/config/ppd
total 400
drwxrwxr-x 2 admin administrators   4096 2021-01-23 12:59 ./
drwxrwx--- 3 admin administrators   4096 2021-01-23 12:55 ../
-rw-r--r-- 1 admin              7 193984 2021-01-23 12:59 OfficePrinter.ppd
-rw-r--r-- 1 admin              7 193957 2021-01-23 12:58 OfficePrinter.ppd.O

[admin] #  docker start cups

[admin] # docker exec -i -t cups ls -al /config/ppd  
total 400
drwxrwxr-x+ 2 root root   4096 Jan 23 17:59 .
drwxrwx---+ 3 root root   4096 Jan 23 17:55 ..
-rw-r--r--+ 1 root lp   193984 Jan 23 17:59 OfficePrinter.ppd
-rw-r--r--+ 1 root lp   193957 Jan 23 17:58 OfficePrinter.ppd.O
```

browser: http://nas.mydomain:631/jobs
cancel prior job, resubmit via iPhone

**Comment by RagingTiger** [comment]
My use case has always involved `HP` printers, and I realize that the issue here may be the `drivers` being installed upon building the `docker image`. You may consider checking out a fork of this repository: https://github.com/webhdx/docker-cups-airprint

In @webhdx's fork of this repository, he added more `drivers` to be installed (which can be seen here in the `Dockerfile`: https://github.com/webhdx/docker-cups-airprint/commit/ae64a8c33d38b59628600a6d09e9e66e4ee7b8c9).

Hopefully this will work better, and (ideally) resolve your issue. If so then I will look at adding additional drivers here.

**Comment by fabriziorizzo** [comment]
@RagingTiger, Thanks... I'll give webdhdx's fork a try.  Nothing else has worked...

**Comment by RagingTiger** [comment]
I will be curious to know if @webhdx's fork (and additional drivers) will help.

If you feel so inclined, let me know if it helps, and I apologize that I have been unable to really help up to this point :(
