### ISSUE TITLE
Printer HP problem

### ISSUE THREAD

**Issue by conan-ed** [RagingTiger/docker-cups-airprint#7]
I could add the printer HP Laser 107a using ppd file OK after download and install the driver for Pi. But the printer status is:
File "/usr/lib/cups/filter/rastertospl" not available: No such file or directory
I tried to create the directories then copy the file rastertospl but same problem even after restart cups. Try to print a test page fail. Got forbidden when view the log.

**Comment by RagingTiger** [comment]
I wonder if this is related to issue #4, which seemed to be an issue with installing the correct printer drivers via the **Dockerfile**. 

As suggested in that issue (https://github.com/RagingTiger/docker-cups-airprint/issues/4#issuecomment-767841561) you may want to try using @webhdx's version: https://github.com/webhdx/docker-cups-airprint.

Let me know if this works.

**Comment by conan-ed** [comment]
Thank for your answer.
How could I use @webhdx's version? The docker create command in his page is the same as you. Do I need to pull his code and build the image myself?

**Comment by RagingTiger** [comment]
That is correct. 

If you look at his [Dockerfile](https://github.com/webhdx/docker-cups-airprint/commit/ae64a8c33d38b59628600a6d09e9e66e4ee7b8c9) he has added more **printer drivers** to his **Docker image** compared to mine.

As you might imagine, when I developed this image the scope was limited to my own specific needs (i.e. the printers I have). So, now that other people have attempted to use it for their own needs, there seems to be reoccurring issues with getting it to work. I conjecture that this has something to do with the correct printer drivers being absent from the **tigerj/cups-airprint** image.

If you wouldn't mind pulling @webhdx's repo [webhdx/docker-cups-airprint](https://github.com/webhdx/docker-cups-airprint), and building his image:
```
$ docker build -t webhdx/cups-airprint .
```
And then try to reproduce the steps you took with my [tigerj/cups-airprint](https://hub.docker.com/r/tigerj/cups-airprint) **Docker** image, we might be able to get a sense of whether or not my **conjecture** is remotely accurate. If it is accurate, then I will add those changes to my **Dockerfile**, if not then we will see if we can figure out what is the nature of the problem.

Either way we will be closer to solving it 🎲

**Comment by conan-ed** [comment]
I just build webhdx image ok but unfortunately it still do not have the driver for my printer (HP Laser 107a). Is there any way I could add the driver I downloaded from HP before building the image?

**Comment by conan-ed** [comment]
Maybe I could insert this:
_wget https://ftp.hp.com/pub/softlib/software13/printers/CLP150/uld-hp_V1.00.39.12_00.15.tar.gz
tar -xvf uld-hp_V1.00.39.12_00.15.tar.gz
cd uld/
sudo ./install.sh_
into the Docker file after the apt-get install command?

**Comment by RagingTiger** [comment]
Yes you could do that (if that is indeed the problem).

Can you post more information about the commands you are running? For example what is the full docker command you are using? What is full error message(s) you are getting etc .....

Also this post may help: https://askubuntu.com/questions/512046/how-to-install-rastertospl-in-my-usr-lib-cups-filter

**Comment by conan-ed** [comment]
I tried to add this in Docker file (i downloaded the driver then decompressed to folder uld in the same folder as the Dockerfile):

_RUN mkdir -p /tmp
COPY uld /tmp/uld
RUN /tmp/uld/install-printer.sh_

but the script install-printer.sh seams not run correctly. Dont know what to do next.
For the rastertospl-in-my-usr-lib-cups-filter i tried to copy it but the printer fail to print test page.

**Comment by conan-ed** [comment]
I want to add some comments for ppl who want to add cups printer to win 10:
1. If use the printer automatic listed by windows, the printer works but very slow to start each print
2. For faster print choose The printer I want isn't listed then add printer by name such as "http://192.168.1.100:631/printers/HP_Laser_107"
3. When choosing driver for printer, if I choose the right driver (HP 10x for my case) then the printer only print meta data instead of the actual spool data. Choose a postscript driver instead (example MS PS class driver) then the printer will work correctly!
