### ISSUE TITLE
hp plugin

### ISSUE THREAD

**Issue by justin-eng** [RagingTiger/docker-cups-airprint#8]
I setup a HP_M126a, and suffer "Filter failed".
need to be installed hp plugin.
but while I execute the command, looks no connection.
how can i process?
-------------------
| DOWNLOAD PLUGIN |

Checking for network connection...                                                                                        Downloading plug-in from: 
Downloading plug-in: [\                                                                              ] 0%  -^Cerror: User exit

**Comment by RagingTiger** [comment]
It may have something to do with this: 
https://unix.stackexchange.com/questions/77139/filter-failed-from-hplip
https://bbs.archlinux.org/viewtopic.php?id=201719

This is probably a driver issue (again #7 #4 #5) .....

If you could, please list as much information about the following:

+ Platform Arch (i.e. AMD64, ARM64, ARMv7, etc ....)
+ Any/All **Docker** commands used
+ Model of printer
+ Full print our of error message

I'll do my best to help you trouble shoot this, but realistically there's very little I can do here. It sounds like a **driver** issue, and it may require that you fork this repo and add your own **printer drivers** to the **Dockerfile**.

But post the above information as requested and I shall see if I can help 😅

**Comment by justin-eng** [comment]
Platform Arch: i7100(x86-64)
Docker commands: docker -it exec cups /bin/bash
**Plug-in version: 3.16.3
Installed HPLIP version: 3.16.3
Number of files to install: 42**
Model of printer: HP_LaserJet_Pro_MFP_M126a
error at Jobs: stopped "Filter failed"
detailed output as below

root@omv:/# hp-setup -i

HP Linux Imaging and Printing System (ver. 3.16.3)
Printer/Fax Setup Utility ver. 9.0

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

(Note: Defaults for each question are maked with a '*'. Press <enter> to accept the default.)


--------------------------------
| SELECT CONNECTION (I/O) TYPE |
--------------------------------

  Num       Connection  Description                                               
            Type                                                                  
  --------  ----------  ----------------------------------------------------------
  0*        usb         Universal Serial Bus (USB)                                
  1         net         Network/Ethernet/Wireless (direct connection or JetDirect)
  2         par         Parallel Port (LPT:)                                      

Enter number 0...2 for connection type (q=quit, enter=usb*) ? 0

Using connection type: usb
                                                                                                                           
Setting up device: hp:/usb/HP_LaserJet_Pro_MFP_M126a?serial=CNBKL5M38D



------------------------
| PLUG-IN INSTALLATION |
------------------------


HP Linux Imaging and Printing System (ver. 3.16.3)
Plugin Download and Install Utility ver. 2.1

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

warning: It is not recommended to run 'hp-plugin' in a root mode.

HP Linux Imaging and Printing System (ver. 3.16.3)
Plugin Download and Install Utility ver. 2.1

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

error: PolicyKit support requires DBUS or PolicyKit support files missing
(Note: Defaults for each question are maked with a '*'. Press <enter> to accept the default.)


-----------------------------------------
| PLUG-IN INSTALLATION FOR HPLIP 3.16.3 |
-----------------------------------------

  Option      Description                                       
  ----------  --------------------------------------------------
  d           Download plug-in from HP (recommended)            
  p           Specify a path to the plug-in (advanced)          
  q           Quit hp-plugin (skip installation)                

Enter option (d=download*, p=specify path, q=quit) ? d

-------------------
| DOWNLOAD PLUGIN |
-------------------

Checking for network connection...                                                                                        Downloading plug-in from: 
Downloading plug-in: [\                                                                              ] 0% Receiving digital keys: /usr/bin/gpg --homedir /root/.hplip/.gnupg --no-permission-warning --keyserver pgp.mit.edu --recv-keys 0x4ABA2F66DBD5A95894910E0673D770CDA59047B9                                                                                              

----------------------
| INSTALLING PLUG-IN |
----------------------

Creating directory plugin_tmp
Verifying archive integrity... All good.
Uncompressing HPLIP 3.16.3 Plugin Self Extracting Archive................................................

HP Linux Imaging and Printing System (ver. 3.16.3)
Plugin Installer ver. 3.0

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

Plug-in version: 3.16.3
Installed HPLIP version: 3.16.3
Number of files to install: 42

You must agree to the license terms before installing the plug-in:

LICENSE TERMS FOR HP Linux Imaging and Printing (HPLIP) Driver Plug-in                                                     


These License Terms govern your Use of the HPLIP Driver Plug-in Software (the "Software"). USE OF THE SOFTWARE INCLUDING,  
WITHOUT LIMITATION, ANY DOCUMENTATION, IS SUBJECT TO THESE LICENSE TERMS AND THE APPLICABLE AS-IS WARRANTY STATEMENT. BY   
DOWNLOADING AND INSTALLING THE SOFTWARE, YOU ARE AGREEING TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO ALL OF THESE  
TERMS, DO NOT DOWNLOAD AND INSTALL THE SOFTWARE ON YOUR SYSTEM.                                                            


1. License Grant. HP grants you a license to Use one copy of the Software with HP printing products only. "Use" includes   
using, storing, loading, installing, executing, and displaying the Software. You may not modify the Software or disable any
licensing or control features of the Software.                                                                             


2. Ownership. The Software is owned and copyrighted by HP or its third party suppliers. Your license confers no title to,  
or ownership in, the Software and is not a sale of any rights in the Software. HP's third party suppliers may protect their
rights in the Software in the event of any violation of these license terms.                                               


3. Copies and Adaptations. You may only make copies or adaptations of the Software for archival purposes or when copying or
adaptation is an essential step in the authorized Use of the Software. You must reproduce all copyright notices in the     
original Software on all copies or adaptations. You may not copy the Software onto any public network.                     


4. No Disassembly. You may not Disassemble the Software unless HP's prior written consent is obtained. "Disassemble"       
includes disassembling, decompiling, decrypting, and reverse engineering. In some jurisdictions, HP's consent may not be   
required for limited Disassembly. Upon request, you will provide HP with reasonably detailed information regarding any     
Disassembly.                                                                                                               


5. No Transfer. You may not assign, sublicense or otherwise transfer all or any part of these License Terms or the         
Software.                                                                                                                  


6. Termination. HP may terminate your license, upon notice, for failure to comply with any of these License Terms. Upon    
termination, you must immediately destroy the Software, together with all copies, adaptations and merged portions in any   
form.                                                                                                                      


7. Export Requirements. You may not export or re-export the Software or any copy or adaptation in violation of any         
applicable laws or regulations.                                                                                            


8. U.S. Government Restricted Rights. The Software has been developed entirely at private expense. It is delivered and     
licensed, as defined in any applicable DFARS, FARS, or other equivalent federal agency regulation or contract clause, as   
either "commercial computer software" or "restricted computer software", whichever is applicable. You have only those      
rights provided for such Software by the applicable clause or regulation or by these License Terms.                        


9. DISCLAIMER OF WARRANTIES. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HP AND ITS SUPPLIERS PROVIDE THE SOFTWARE  
"AS IS" AND WITH ALL FAULTS, AND HEREBY DISCLAIM ALL OTHER WARRANTIES AND CONDITIONS, EITHER EXPRESS, IMPLIED, OR          
STATUTORY, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF TITLE AND NON-INFRINGEMENT, ANY IMPLIED WARRANTIES, DUTIES OR      
CONDITIONS OF MERCHANTABILITY, OF FITNESS FOR A PARTICULAR PURPOSE, AND OF LACK OF VIRUSES ALL WITH REGARD TO THE SOFTWARE.
Some states/jurisdictions do not allow exclusion of implied warranties or limitations on the duration of implied           
warranties, so the above disclaimer may not apply to you in its entirety.                                                  


10. LIMITATION OF LIABILITY. Notwithstanding any damages that you might incur, the entire liability of HP and any of its   
suppliers under any provision of this agreement and your exclusive remedy for all of the foregoing shall be limited to the 
greater of the amount actually paid by you separately for the Software or U.S. $5.00. TO THE MAXIMUM EXTENT PERMITTED BY   
APPLICABLE LAW, IN NO EVENT SHALL HP OR ITS SUPPLIERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL,                               
INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS OR CONFIDENTIAL  
OR OTHER INFORMATION, FOR BUSINESS INTERRUPTION, FOR PERSONAL INJURY, FOR LOSS OF PRIVACY ARISING OUT OF OR IN ANY WAY     
RELATED TO THE USE OF OR INABILITY TO USE THE SOFTWARE, OR OTHERWISE IN CONNECTION WITH ANY PROVISION OF THIS AGREEMENT,   
EVEN IF HP OR ANY SUPPLIER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND EVEN IF THE REMEDY FAILS OF ITS         
ESSENTIAL PURPOSE. Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential       
damages, so the above limitation or exclusion may not apply to you.                                                        

Do you accept the license terms for the plug-in (y=yes*, n=no, q=quit) ? y
Plugin installation failed
error: Plugin installation failed

Done.                                                                                                                      
Done.

---------------------
| PRINT QUEUE SETUP |
---------------------


Please enter a name for this print queue (m=use model name:'HP_LaserJet_Pro_MFP_M126a'*, q=quit) ?m
Using queue name: HP_LaserJet_Pro_MFP_M126a
Locating PPD file... Please wait.

Found PPD file: drv:///hpcups.drv/hp-laserjet_pro_mfp_m126a.ppd
Description: 

Note: The model number may vary slightly from the actual model number on the device.

Does this PPD file appear to be the correct one (y=yes*, n=no, q=quit) ? 
Enter a location description for this printer (q=quit) ?home
Enter additonal information or notes for this printer (q=quit) ?HP_M126a

Adding print queue to CUPS:
Device URI: hp:/usb/HP_LaserJet_Pro_MFP_M126a?serial=CNBKL5M38D
Queue name: HP_LaserJet_Pro_MFP_M126a
PPD file: drv:///hpcups.drv/hp-laserjet_pro_mfp_m126a.ppd
Location: home
Information: HP_M126a


---------------------
| PRINTER TEST PAGE |
---------------------


Would you like to print a test page (y=yes*, n=no, q=quit) ? y
warning: hp-testpage should not be run as root/superuser.

HP Linux Imaging and Printing System (ver. 3.16.3)
Testpage Print Utility ver. 6.0

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

Printing test page to printer HP_LaserJet_Pro_MFP_M126a...
request id is HP_LaserJet_Pro_MFP_M126a-5 (1 file(s))
Test page has been sent to printer.

note: If an error occured, or the test page failed to print, refer to the HPLIP website
note: at: http://hplip.sourceforge.net for troubleshooting and support.


Done.

Done.
root@omv:/#

**Comment by justin-eng** [comment]
Hi Tiger,
I used another docker(), and it is ok. paste the difference as below.
----------------------------
Description:	HP LaserJet Pro MFP M126a
Location:	home
Driver:	HP LaserJet Pro MFP m126a, **hpcups 3.18.12 (color)**
Connection:	hp:/usb/HP_LaserJet_Pro_MFP_M126a?serial=CNBKL5M38D
Defaults:	job-sheets=none, none media=iso_a4_210x297mm sides=one-sided

Description:	HP LaserJet Pro MFP M126a
Location:	home
Driver:	HP LaserJet Pro MFP m126a, **hpcups 3.16.3, requires proprietary plugin (color)**
Connection:	hp:/usb/HP_LaserJet_Pro_MFP_M126a?serial=CNBKL5M38D
Defaults:	job-sheets=none, none media=iso_a4_210x297mm sides=one-sided
------------------------------
it should be driver issue. even i update the system(apt dist-upgrade). can't change the driver version.
maybe you can update the driver?

**Comment by RagingTiger** [comment]
@justin-eng Interesting, so your printer worked with **hpcups 3.18.12** but not with **hpcups 3.16.3** ? And this resolved your issue?

**Comment by justin-eng** [comment]
actually yes. compare the description of the hp driver as above. 3.16 require something, but 3.18 even 3.20 not. and i found many hp printers like this.

**Comment by RagingTiger** [comment]
Trouble shooting section has been added to README to address this issue, and how to resolve it.

Thanks @justin-eng.
